<template>
  <div >
      <new-header :p="p" :key="index" v-for="(p,index) in news"></new-header>
      <new-section :q="q" v-for="(q,index1) in news"></new-section>
  </div>
</template>

<script>
import newHeader from '../components/new/newHeader'
import newSection from '../components/new/newSection'
export default {
  name: 'seasonNew',
  components:{newHeader,newSection},
  data(){
      return {
            "news":[
                {
                    "newHeader":[
                        {
                            "pic1":"/img/new/n1.png",
                            "pic2":"/img/new/n2.png",
                            "desc1":"快来尝尝鲜吧！",
                            "desc2":"24季新品上架"
                        }
                    ],
                    "newSection":[
                        {
                            "name":"全部",
                            "newSectionList":[
                                {
                                    "pic":"/img/new/n4.png",
                                    "title":"沙棘冷榨果汁饮料",
                                    "price":"158"
                                },
                                {
                                    "pic":"/img/new/n5.png",
                                    "title":"免费冲泡酸梅汤",
                                    "price":"45"
                                },
                                {
                                    "pic":"/img/new/n6.png",
                                    "title":"水果冰淇淋",
                                    "price":"48"
                                },
                                {
                                    "pic":"/img/new/n7.png",
                                    "title":"东北赵三姑辣椒酱",
                                    "price":"168"
                                },
                                {
                                    "pic":"/img/new/n8.png",
                                    "title":"古法熬制南枣核桃",
                                    "price":"45"
                                },
                                {
                                    "pic":"/img/new/n9.png",
                                    "title":"无添加空心山楂",
                                    "price":"39"
                                },
                                {
                                    "pic":"/img/new/n10.png",
                                    "title":"青岛香酥小黄鱼",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n11.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n12.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n13.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n14.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n15.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n16.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"54"
                                },
                                {
                                    "pic":"/img/new/n17.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"76"
                                },
                                {
                                    "pic":"/img/new/n18.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"39"
                                },
                                {
                                    "pic":"/img/new/n19.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"99"
                                },
                                {
                                    "pic":"/img/new/n20.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"65"
                                },
                                {
                                    "pic":"/img/new/n21.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"44"
                                }
                            ]
                        },
                        {
                            "name":"食材",
                            "newSectionList":[
                                {
                                    "pic":"/img/new/n11.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n12.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n13.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n14.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n15.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n16.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"54"
                                },
                                {
                                    "pic":"/img/new/n17.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"76"
                                },
                                {
                                    "pic":"/img/new/n18.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"39"
                                },
                                {
                                    "pic":"/img/new/n19.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"99"
                                },
                                {
                                    "pic":"/img/new/n20.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"65"
                                },
                                {
                                    "pic":"/img/new/n21.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"44"
                                }
                            ]
                        },
                        {
                            "name":"轻食",
                            "newSectionList":[
                                {
                                    "pic":"/img/new/n6.png",
                                    "title":"水果冰淇淋",
                                    "price":"48"
                                },
                                {
                                    "pic":"/img/new/n7.png",
                                    "title":"东北赵三姑辣椒酱",
                                    "price":"168"
                                },
                                {
                                    "pic":"/img/new/n8.png",
                                    "title":"古法熬制南枣核桃",
                                    "price":"45"
                                },
                                {
                                    "pic":"/img/new/n9.png",
                                    "title":"无添加空心山楂",
                                    "price":"39"
                                },
                                {
                                    "pic":"/img/new/n10.png",
                                    "title":"青岛香酥小黄鱼",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n11.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n12.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n13.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n14.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n15.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n16.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"54"
                                },
                                {
                                    "pic":"/img/new/n17.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"76"
                                },
                                {
                                    "pic":"/img/new/n18.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"39"
                                },
                                {
                                    "pic":"/img/new/n20.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"65"
                                },
                                {
                                    "pic":"/img/new/n21.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"44"
                                }
                            ]
                        },
                        {
                            "name":"饮品",
                            "newSectionList":[
                                {
                                    "pic":"/img/new/n5.png",
                                    "title":"免费冲泡酸梅汤",
                                    "price":"45"
                                },
                                {
                                    "pic":"/img/new/n6.png",
                                    "title":"水果冰淇淋",
                                    "price":"48"
                                },
                                {
                                    "pic":"/img/new/n7.png",
                                    "title":"东北赵三姑辣椒酱",
                                    "price":"168"
                                },
                                {
                                    "pic":"/img/new/n8.png",
                                    "title":"古法熬制南枣核桃",
                                    "price":"45"
                                },
                                {
                                    "pic":"/img/new/n9.png",
                                    "title":"无添加空心山楂",
                                    "price":"39"
                                },
                                {
                                    "pic":"/img/new/n12.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n13.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n14.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n15.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n16.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"54"
                                },
                                {
                                    "pic":"/img/new/n17.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"76"
                                },
                                {
                                    "pic":"/img/new/n18.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"39"
                                },
                                {
                                    "pic":"/img/new/n19.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"99"
                                },
                                {
                                    "pic":"/img/new/n20.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"65"
                                },
                                {
                                    "pic":"/img/new/n21.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"44"
                                }
                            ]
                        },
                        {
                            "name":"美物",
                            "newSectionList":[
                                {
                                    "pic":"/img/new/n7.png",
                                    "title":"东北赵三姑辣椒酱",
                                    "price":"168"
                                },
                                {
                                    "pic":"/img/new/n8.png",
                                    "title":"古法熬制南枣核桃",
                                    "price":"45"
                                },
                                {
                                    "pic":"/img/new/n9.png",
                                    "title":"无添加空心山楂",
                                    "price":"39"
                                },
                                {
                                    "pic":"/img/new/n10.png",
                                    "title":"青岛香酥小黄鱼",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n11.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n12.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n13.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n14.png",
                                    "title":"吉稻粮仓有机米",
                                    "price":"68"
                                },
                                {
                                    "pic":"/img/new/n15.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"24"
                                },
                                {
                                    "pic":"/img/new/n16.png",
                                    "title":"福州手撕肉豆干",
                                    "price":"54"
                                }
                            ]
                        },
                    ]
                }

            ]
      }
  }
}
</script>
<style>
  @import "../assets/css/new.css";
  /* .changeFlex{
    height: 100%;
    display: flex;
    flex-direction: column;
  } */
</style>

